spring:
  profiles: default
  session.store-type: HASH_MAP
  application:
    name: ${MICROSERVICE_NAME:place-search-api}
    namespace: ${CLOUD_NAMESPACE:unknown}
    cloud_namespace: ${CLOUD_NAMESPACE:unknown}
  redis:
    host: localhost
    port: 6379

server:
  address: "0.0.0.0"
  port: 8096
  tomcat:
    accesslog.enabled: false
    max-http-post-size: 65536
  session:
    servlet.timeout: 300000S
  max-http-header-size: 65536

here-place-search-api-service:
  placesearch:
    url: ${PLACE_SEARCH_API:https://places.demo.api.here.com}
    appId: devportal-demo-20180625
    appCode: 9v2BkviRwi9Ot26kp2IysQ
    connect-timeout: 600000
    call-retry:
      attempts: 1

geocode-search-hereapi-service:
  url: ${GEO_SEARCH_API:https://geocode.search.hereapi.com}
  apiKey: jiyEuMzpr7Qwj1ZG5bkRcYRZM_CRZUuM-EBmsc_Iu88

---